// <auto-generated />
namespace MedicationTherapyManagement.TriggersMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class addindReviewedColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addindReviewedColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201403231900106_addindReviewedColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
