// <auto-generated />
namespace MedicationTherapyManagement.TriggersMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class addpatientidtocases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpatientidtocases));
        
        string IMigrationMetadata.Id
        {
            get { return "201406020212427_add-patient-id-to-cases"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
